sources:
  - name: raw
    description: Raw data from CSV files
    database: postgres
    schema: raw

    tables:
      - name: census_g01
      - name: census_g02
      - name: lgas_code
      - name: lgas_suburb
      - name: listing_data